public: false
type: "docs"
tags:
  - "digital preservation"
  - "archivematica"
title: "Guide to Using Archivematica at the RAC"
description: "Local Archivematica documentation"
pages:
  - ["Guide to Using Archivematica at the RAC", "index"]
  - ["Transfer Structure", "transferStructure"]
  - ["Digitization Ingest", "digitizationIngest"]
  - ["Born digital ingest", "Born digital ingest into Archivematica workflow"]
  - ["Automation Tools", "automationTools"]
  - ["ArchivesSpace DIP Upload", "archivesspaceDIPupload"]
  - ["PREMIS Rights", "premisRights"]
  - ["Processing Configuration", "processingConfiguration"]
  - ["Storage Service", "storageService"]
