public: true
type: "docs"
title: "Archivematica Guide"
description: "Local Archivematica documentation."
pages:
  - ["Archivematica Overview", "index"]
  - ["Set up for Transfer", "transferAndSetup"]
  - ["Administration", "administration"]
  - ["PREMIS Rights", "premis"]
  - ["Updating", "updating"]
  - ["Appendix", "appendix"]
