public: true
type: "docs"
category: "preservation"
tags:
  - "workflow"
title: "Guide to Using Archivematica"
description: "Local Archivematica documentation."
pages:
  - ["Archivematica Overview", "index"]
  - ["Set up for Transfer", "transferAndSetup"]
  - ["Administration", "administration"]
  - ["Updating", "updating"]
  - ["Appendix", "appendix"]
