public: false
type: "docs"
tags:
  - "digital preservation"
  - "archivematica"
title: "Guide to Using Archivematica"
description: "Local Archivematica documentation"
pages:
  - ["Archivematica Overview", "index"]
  - ["Set up for Transfer", "transferAndSetup"]
  - ["Ingest", "ingest"]
  - ["Workflows by Content Type", "workflows"]
  - ["Administration", "administration"]
  - ["Appendix", "appendix"]
